# Generated by Django 4.2.7 on 2024-01-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Smestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=255)),
                ('kapacitet', models.PositiveIntegerField()),
                ('cena_nocenja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destinacija')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_dolaska', models.DateField()),
                ('datum_odlaska', models.DateField()),
                ('broj_gostiju', models.PositiveIntegerField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('smestaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.smestaj')),
            ],
        ),
    ]
