# Generated by Django 4.2.7 on 2024-01-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smestaj',
            new_name='Smjestaj',
        ),
        migrations.RenameField(
            model_name='rezervacija',
            old_name='smestaj',
            new_name='smjestaj',
        ),
    ]
