# Generated by Django 4.2.7 on 2024-01-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_smestaj_smjestaj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmjestajRezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezervacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rezervacija')),
                ('smjestaji', models.ManyToManyField(to='main.smjestaj')),
            ],
        ),
        migrations.CreateModel(
            name='DodatniDetalji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neki_detalji', models.TextField()),
                ('rezervacija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.rezervacija')),
            ],
        ),
    ]
